.\" Manpage for suseha-plugin.
.\" Contact jkalcic@suse.com to correct errors or typos.
.TH man 1 "25 March 2013" "1.0" "suseha-plugin man page"
.SH NAME
suseha-plugin \- Supportconfig Plugin for High Availability Extention
.SH DESCRIPTION
Supportconfig plugin for SUSE Linux Enteprise High Availability Extension. It is based on a customized version of "hahealth", a tool to perform basic health check against the core components of a Linux-HA clusters.

hahealth is, in turn, based on hb_report from where it takes part of the information it shows up. By default, the plugin creates a hb_report based on the last day from which it extracts the most relevant facts. The hb_report created is eventually attached to the supportconfig for further analysis. This behavior and other default options can be modified with file suseha-plugin.conf

Along with the hb_report of the last day, the plugin will create and attach to the supportconfig also a file named "basic-health-check-ha.txt" which contains an easy-to-read report of the checks it performs.
.SH FILES
/usr/lib/supportconfig/plugins/suseha-plugin
/usr/lib/supportconfig/plugins/suseha-plugin.conf
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
.BR hb_report(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Jan Kalcic (jkalcic@suse.com)
